version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run:
          name: Build
          command: |
            make build
  publish:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run:
          name: Publish
          command: |
            make publish
workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - publish:
          filters:
            branches:
              only: master
          requires:
            - build
          context: gradle-plugin